title: "Todd Cauet"
description: "site perso de Todd Cauet"
baseurl: ""
url: https://toddcauet.github.io

plugins:
  - jekyll-include-cache

remote_theme: hydecorp/hydejack@v9.2.1

hydejack:
  dark_mode:
    dynamic: true
    icon:    true
    always:  false

author:
  name: Todd Cauet
  email:
  about: |
    Hi i'm Todd Cauet
  social:
    twitter: ToddCauet
    github: toddcauet

menu:
  - title: Resume
    url: /resume